import type { Metadata } from "next";
import {Road_Rage, Roboto} from "next/font/google";
import "./globals.css";
import {Navbar} from "@/components/navbar";
import {Card} from "@/components/ui/card";
import {BookingStep} from "@/components/booking-step";
import {TicketContextProvider} from "@/store/ticket-context";


const roadRage = Road_Rage({
    subsets: ["latin"],
    weight: "400"
})


const roboto = Roboto({
    subsets: ["latin"],
    weight: ["400", "500", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roadRage.className} ${roboto.className}  bg-[#02191D] text-white`}
      >
      <div className="m-5 " >
          <Navbar/>
          <TicketContextProvider>
              <Card className="mt-3 bg-backgroundLight p-5" >
                  <BookingStep/>

                  {children}
              </Card>
          </TicketContextProvider>
      </div>
      </body>
    </html>
  );
}
